services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB_ADMIN?Variable not set}
      POSTGRES_USER: ${POSTGRES_USER_ADMIN?Variable not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_ADMIN?Variable not set}
      PGDATA: /var/lib/postgresql/data/pgdata
#      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
#      - ./init-scripts:/docker-entrypoint-initdb.d
#      - ./postgres.conf:/etc/postgresql/postgresql.conf
    command: >
      postgres
       -c hba_file=/etc/postgresql/pg_hba.conf
       -c listen_addresses='*'
#      -c config_file=/etc/postgresql/postgresql.conf
#      -c shared_preload_libraries=pg_stat_statements
    restart: unless-stopped
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U myapp_user -d myapp_db"]
#      interval: 30s
#      timeout: 10s
#      retries: 3

volumes:
  postgres_data: