[project]
name = "fastapi-starter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.121.3",
    "granian>=2.6.0",
]

[dependency-groups]
dev = [
    "granian[reload]>=2.6.0",
    "pytest>=9.0.1",
]
